tapi:
  command: go
  args:
    - run
    - -mod=vendor
    - cmd/tremord/main.go
    - -db-name=tremortest
    - -sqs-endpoint=http://localhost:4100
    - -oidc-aud=http://localhost:8080/api
    - -workers-url=http://localhost:8082
  dir: $HOME/Work/tremor/api.git
  env:
    BASE_URL: http://localhost:8080
    AWS_ACCESS_KEY_ID: foo
    AWS_SECRET_ACCESS_KEY: bar
    OIDC_CLIENT_ID: 4Bmt7q2bYYisEcMN92l3WfxLrCs0yCso
    OIDC_CLIENT_SECRET: GIXzQAKKRnpWaaP-1qO9NZKswvxoUm3UmChL6REeFAgCn2tJHMjN5Fypqo4E0ApL
tworkers:
  command: go
  args:
    - run
    - -mod=vendor
    - cmd/workers/main.go
    - -addr=0.0.0.0:8082
    - -sqs-endpoint=http://localhost:4100
    - -oidc-audience=http://localhost:8082/api
  dir: $HOME/Work/tremor/workers.git
  env:
    BASE_URL: http://localhost:8082
    API_URL: http://localhost:8080
    STORAGE_URL: http://localhost:8081
    AWS_ACCESS_KEY_ID: foo
    AWS_SECRET_ACCESS_KEY: bar
    OIDC_CLIENT_ID: 125B0p5JIK3FnNtN2Ripyu9Fo0NyZ3Kv
    OIDC_CLIENT_SECRET: tA64cDJ5qnQQi7rgKdV6Ig4OzKFUpxAzPgIGOkmXriY-qlxNQiB4hWOt7Vq-Ypcm
tstorage:
  command: go
  args:
    - run
    - -mod=vendor
    - cmd/storaged/main.go
    - -addr=0.0.0.0:8081
    - -oidc-aud=http://localhost:8081/api
  dir: $HOME/Work/tremor/storage.git
  env:
    BASE_URL: http://localhost:8081
    API_URL: http://localhost:8080

