set nocompatible

let s:config_path = $HOME.'/.vim/'
let s:config_files = [
	\'functions.vim',
	\'plugins.vim',
	\'common.vim',
	\'plugin_conf.vim',
	\'languages.vim',
	\'mappings.vim',
	\]

for file in s:config_files
	if filereadable(s:config_path.file)
		exec "so ".s:config_path.file
	endif
endfor
