" Skip init for vim-tiny or vim-small
if 0 | endif

" Don't be compatible with Vi
if &compatible
    set nocompatible
endif

" Disable filetypes
filetype off

let s:config_path = $HOME.'/.vim/config/'
let s:config_files = [
            \'plugins.vim',
            \'common.vim',
            \'plugin_config.vim',
            \'gui.vim',
            \]

for file in s:config_files
    if filereadable(s:config_path.file)
        exec "so ".s:config_path.file
    endif
endfor


if &termencoding == ""
        let &termencoding = &encoding
endif
set encoding=utf-8

" Enable Syntax Highlighting
syntax on

" Enable filetype handling
filetype plugin indent on


" Process all of the configuration files
for filename in sort(split(glob('~/.vim/config/*.vim'), '\n'))
        execute 'source '.filename
endfor

